apiVersion: v1
kind: Service
metadata:
  name: mongo-cfgsvr-svc-a
  labels:
    name: mongo-cfgsvr-svc-a
spec:
  clusterIP: None
  ports:
  - port: 27019
    targetPort: 27019
    protocol: TCP
  selector:
    name: mongo-configsvr-node1
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-cfgsvr-svc-b
  labels:
    name: mongo-cfgsvr-svc-b
spec:
  clusterIP: None
  ports:
  - port: 27019
    targetPort: 27019
    protocol: TCP
  selector:
    name: mongo-configsvr-node2
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-cfgsvr-svc-c
  labels:
    name: mongo-cfgsvr-svc-c
spec:
  clusterIP: None
  ports:
  - port: 27019
    targetPort: 27019
    protocol: TCP
  selector:
    name: mongo-configsvr-node3
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-configsvr-rc1
  labels:
    name: mongo-configsvr-rc
spec:
  replicas: 1
  selector:
    name: mongo-configsvr-node1
  template:
    metadata:
      labels:
        name: mongo-configsvr-node1
    spec:
      containers:
      - name: mongo-configsvr-node1
        image: index.caicloud.io/caicloud/mongo:3.2
        command:
        - mongod
        - "--configsvr"
        - "--replSet"
        - configReplSet
        ports:
        - containerPort: 27019
        volumeMounts:
        - name: mongo-persistent-storage1
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage1
        emptyDir: {}
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-configsvr-rc2
  labels:
    name: mongo-configsvr-rc
spec:
  replicas: 1
  selector:
    name: mongo-configsvr-node2
  template:
    metadata:
      labels:
        name: mongo-configsvr-node2
    spec:
      containers:
      - name: mongo-configsvr-node2
        image: index.caicloud.io/caicloud/mongo:3.2
        command:
        - mongod
        - "--configsvr"
        - "--replSet"
        - configReplSet
        ports:
        - containerPort: 27019
        volumeMounts:
        - name: mongo-persistent-storage2
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage2
        emptyDir: {}
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-configsvr-rc3
  labels:
    name: mongo-configsvr-rc
spec:
  replicas: 1
  selector:
    name: mongo-configsvr-node3
  template:
    metadata:
      labels:
        name: mongo-configsvr-node3
    spec:
      containers:
      - name: mongo-configsvr-node3
        image: index.caicloud.io/caicloud/mongo:3.2
        command:
        - mongod
        - "--configsvr"
        - "--replSet"
        - configReplSet
        ports:
        - containerPort: 27019
        volumeMounts:
        - name: mongo-persistent-storage3
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage3
        emptyDir: {}